import { MovieRating, type Movie } from "../../types/types";

export const mockMovies: Movie[] = [
  {
    id: 1,
    name: "A Grande Aventura",
    originalName: "The Great Adventure",
    casting: "João Silva, Maria Souza",
    direction: "Carlos Pereira",
    synopsis: "Uma jornada emocionante através de terras desconhecidas.",
    genre: "Aventura",
    duration: 115,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2023-05-12"),
    posterUrl: "https://picsum.photos/60?random=1",
    active: true,
  },
  {
    id: 2,
    name: "Noite de Mistério",
    originalName: "Mystery Night",
    casting: "Ana Costa, Roberto Lima",
    direction: "Fernanda Rocha",
    synopsis: "Um suspense que prende a atenção até o último minuto.",
    genre: "Suspense",
    duration: 98,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2024-02-18"),
    posterUrl: "https://picsum.photos/60?random=2",
    active: true,
  },
  {
    id: 3,
    name: "Comédia do Bairro",
    originalName: "Neighborhood Comedy",
    casting: "Pedro Alves, Carla Mendes",
    direction: "Luiz Andrade",
    synopsis: "Uma comédia leve sobre vizinhos e confusões cotidianas.",
    genre: "Comédia",
    duration: 105,
    rating: MovieRating.LIVRE,
    releaseDate: new Date("2022-11-05"),
    posterUrl: "https://picsum.photos/60?random=3",
    active: false,
  },
];
