import { MovieRating, MovieStatus, type Movie } from "../../types/types";

export const mockMovies: Movie[] = [
  {
    id: 1,
    name: "A Grande Aventura",
    originalName: "The Great Adventure",
    casting: "João Silva, Maria Souza",
    direction: "Carlos Pereira",
    synopsis: "Uma jornada emocionante através de terras desconhecidas.",
    genre: "Aventura",
    duration: 115,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2023-05-12"),
    posterUrl: "https://picsum.photos/60?random=1",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 2,
    name: "Noite de Mistério",
    originalName: "Mystery Night",
    casting: "Ana Costa, Roberto Lima",
    direction: "Fernanda Rocha",
    synopsis: "Um suspense que prende a atenção até o último minuto.",
    genre: "Suspense",
    duration: 98,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2024-02-18"),
    posterUrl: "https://picsum.photos/60?random=2",
    movieStatus: MovieStatus.FORA_DE_CARTAZ,
    active: true,
  },
  {
    id: 3,
    name: "Comédia do Bairro",
    originalName: "Neighborhood Comedy",
    casting: "Pedro Alves, Carla Mendes",
    direction: "Luiz Andrade",
    synopsis: "Uma comédia leve sobre vizinhos e confusões cotidianas.",
    genre: "Comédia",
    duration: 105,
    rating: MovieRating.LIVRE,
    releaseDate: new Date("2022-11-05"),
    posterUrl: "https://picsum.photos/60?random=3",
    movieStatus: MovieStatus.PRE_VENDA,
    active: false,
  },
  {
    id: 4,
    name: "A Última Canção",
    originalName: "The Last Song",
    casting: "Mariana Reis, Felipe Duarte",
    direction: "Ana Martins",
    synopsis: "Uma história emocional sobre amor e reconciliação.",
    genre: "Drama",
    duration: 124,
    rating: MovieRating.DOZE,
    releaseDate: new Date("2021-08-20"),
    posterUrl: "https://picsum.photos/60?random=4",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 5,
    name: "Corrida Mortal",
    originalName: "Deadly Run",
    casting: "Lucas Barros, Paula Lima",
    direction: "Roberto Faria",
    synopsis: "Ação intensa em alta velocidade e reviravoltas.",
    genre: "Ação",
    duration: 103,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2020-11-11"),
    posterUrl: "https://picsum.photos/60?random=5",
    movieStatus: MovieStatus.FORA_DE_CARTAZ,
    active: false,
  },
  {
    id: 6,
    name: "Amor na Estação",
    originalName: "Love at the Station",
    casting: "Carolina Nunes, Tiago Melo",
    direction: "Luísa Carvalho",
    synopsis: "Comédia romântica ambientada numa estação de trem.",
    genre: "Romance",
    duration: 95,
    rating: MovieRating.DEZ,
    releaseDate: new Date("2019-02-14"),
    posterUrl: "https://picsum.photos/60?random=6",
    movieStatus: MovieStatus.FORA_DE_CARTAZ,
    active: true,
  },
  {
    id: 7,
    name: "Galáxias Paralelas",
    originalName: "Parallel Galaxies",
    casting: "Marcos Pinto, Érica Lobo",
    direction: "Jorge Salazar",
    synopsis: "Aventura sci-fi sobre universos paralelos e escolhas.",
    genre: "Ficção Científica",
    duration: 138,
    rating: MovieRating.QUATORZE,
    releaseDate: new Date("2025-07-01"),
    posterUrl: "https://picsum.photos/60?random=7",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 8,
    name: "Noite de Terror",
    originalName: "Night of Terror",
    casting: "Rafael Gomes, Beatriz Freitas",
    direction: "César Almeida",
    synopsis: "Terror psicológico que mexe com os maiores medos.",
    genre: "Terror",
    duration: 92,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2023-10-31"),
    posterUrl: "https://picsum.photos/60?random=8",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 9,
    name: "Brincando de Gigantes",
    originalName: "Playing Giants",
    casting: "Laura Campos, Igor Santos",
    direction: "Patrícia Moraes",
    synopsis: "Animação familiar sobre amizade e coragem.",
    genre: "Animação",
    duration: 82,
    rating: MovieRating.LIVRE,
    releaseDate: new Date("2022-06-10"),
    posterUrl: "https://picsum.photos/60?random=9",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 10,
    name: "Documentos Perdidos",
    originalName: "Lost Documents",
    casting: "Sérgio Prado",
    direction: "Mariana Tavares",
    synopsis: "Documentário investigativo sobre arquivos esquecidos.",
    genre: "Documentário",
    duration: 68,
    rating: MovieRating.LIVRE,
    releaseDate: new Date("2018-04-22"),
    posterUrl: "https://picsum.photos/60?random=10",
    movieStatus: MovieStatus.FORA_DE_CARTAZ,
    active: false,
  },
  {
    id: 11,
    name: "Suspense na Chuva",
    originalName: "Suspense in the Rain",
    casting: "Helena Rocha, Daniel Amaral",
    direction: "Gustavo Pinto",
    synopsis: "Um thriller de investigação numa cidade chuvosa.",
    genre: "Suspense",
    duration: 111,
    rating: MovieRating.DOZE,
    releaseDate: new Date("2021-09-30"),
    posterUrl: "https://picsum.photos/60?random=11",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 12,
    name: "Reino Encantado",
    originalName: "Enchanted Realm",
    casting: "Isabela Cruz, Paulo Henrique",
    direction: "Renata Simões",
    synopsis: "Fantasia épica com criaturas mágicas e reinos perdidos.",
    genre: "Fantasia",
    duration: 129,
    rating: MovieRating.QUATORZE,
    releaseDate: new Date("2024-12-20"),
    posterUrl: "https://picsum.photos/60?random=12",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 13,
    name: "No Ritmo do Jazz",
    originalName: "To the Jazz Beat",
    casting: "Clara Nogueira, Bruno Paz",
    direction: "Eduardo Lima",
    synopsis: "Musical que celebra a história do jazz urbano.",
    genre: "Musical",
    duration: 101,
    rating: MovieRating.DEZ,
    releaseDate: new Date("2020-03-05"),
    posterUrl: "https://picsum.photos/60?random=13",
    movieStatus: MovieStatus.FORA_DE_CARTAZ,
    active: false,
  },
];
