import { MovieRating, MovieStatus, type Movie } from "../../types/types";

export const mockMovies: Movie[] = [
  {
    id: 1,
    name: "Oppenheimer",
    originalName: "Oppenheimer",
    casting: "Cillian Murphy, Emily Blunt, Matt Damon",
    direction: "Christopher Nolan",
    synopsis:
      "A biographical drama chronicling the life of J. Robert Oppenheimer and the development of the atomic bomb.",
    genre: "Drama/Biografia",
    duration: 180,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2025-01-15"),
    posterUrl: "https://picsum.photos/60?random=1",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 2,
    name: "Dune",
    originalName: "Dune",
    casting: "Timothée Chalamet, Rebecca Ferguson, Zendaya",
    direction: "Denis Villeneuve",
    synopsis:
      "Adaptation of Frank Herbert's novel: a young nobleman becomes embroiled in a war for control of the desert planet Arrakis.",
    genre: "Ficção Científica",
    duration: 155,
    rating: MovieRating.QUATORZE,
    releaseDate: new Date("2025-02-10"),
    posterUrl: "https://picsum.photos/60?random=2",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 3,
    name: "Top Gun: Maverick",
    originalName: "Top Gun: Maverick",
    casting: "Tom Cruise, Miles Teller, Jennifer Connelly",
    direction: "Joseph Kosinski",
    synopsis:
      "A veteran aviator confronts his past while training a new generation of Top Gun pilots.",
    genre: "Ação",
    duration: 131,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2025-03-05"),
    posterUrl: "https://picsum.photos/60?random=3",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 4,
    name: "Barbie",
    originalName: "Barbie",
    casting: "Margot Robbie, Ryan Gosling, America Ferrera",
    direction: "Greta Gerwig",
    synopsis:
      "A colorful and satirical comedy-adventure exploring identity, culture and modern womanhood.",
    genre: "Comédia/Fantasia",
    duration: 114,
    rating: MovieRating.DEZ,
    releaseDate: new Date("2025-04-12"),
    posterUrl: "https://picsum.photos/60?random=4",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 5,
    name: "Avatar: The Way of Water",
    originalName: "Avatar: The Way of Water",
    casting: "Sam Worthington, Zoe Saldaña, Sigourney Weaver",
    direction: "James Cameron",
    synopsis:
      "Continues the saga of the Na'vi as they confront new threats across the oceans of Pandora.",
    genre: "Aventura/Ficção Científica",
    duration: 192,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2025-05-02"),
    posterUrl: "https://picsum.photos/60?random=5",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 6,
    name: "John Wick: Chapter 4",
    originalName: "John Wick: Chapter 4",
    casting: "Keanu Reeves, Laurence Fishburne, Ian McShane",
    direction: "Chad Stahelski",
    synopsis:
      "Ex-hitman John Wick faces new enemies and allies in a high-stakes battle for survival.",
    genre: "Ação",
    duration: 169,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2025-06-18"),
    posterUrl: "https://picsum.photos/60?random=6",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 7,
    name: "Spider-Man: Across the Spider-Verse",
    originalName: "Spider-Man: Across the Spider-Verse",
    casting: "Shameik Moore, Hailee Steinfeld, Jake Johnson",
    direction: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    synopsis:
      "Miles Morales embarks on an epic adventure across the multiverse, facing different versions of Spider-Man.",
    genre: "Animação/Ação",
    duration: 140,
    rating: MovieRating.LIVRE,
    releaseDate: new Date("2025-07-09"),
    posterUrl: "https://picsum.photos/60?random=7",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 8,
    name: "Mission: Impossible – Dead Reckoning",
    originalName: "Mission: Impossible – Dead Reckoning Part One",
    casting: "Tom Cruise, Rebecca Ferguson, Simon Pegg",
    direction: "Christopher McQuarrie",
    synopsis:
      "Ethan Hunt and his team race against time to prevent a global catastrophe in a globe-trotting mission.",
    genre: "Ação",
    duration: 163,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2025-08-21"),
    posterUrl: "https://picsum.photos/60?random=8",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 9,
    name: "Killers of the Flower Moon",
    originalName: "Killers of the Flower Moon",
    casting: "Leonardo DiCaprio, Lily Gladstone, Robert De Niro",
    direction: "Martin Scorsese",
    synopsis:
      "A historical crime drama about the murders of Osage tribe members and the birth of the FBI investigation.",
    genre: "Drama/Crime",
    duration: 206,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2025-09-12"),
    posterUrl: "https://picsum.photos/60?random=9",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 10,
    name: "Guardians of the Galaxy Vol. 3",
    originalName: "Guardians of the Galaxy Vol. 3",
    casting: "Chris Pratt, Zoe Saldana, Dave Bautista",
    direction: "James Gunn",
    synopsis:
      "The Guardians confront new challenges and personal stakes as their saga continues through the cosmos.",
    genre: "Aventura/Sci-Fi",
    duration: 150,
    rating: MovieRating.DEZESSEIS,
    releaseDate: new Date("2025-10-03"),
    posterUrl: "https://picsum.photos/60?random=10",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 11,
    name: "The Batman",
    originalName: "The Batman",
    casting: "Robert Pattinson, Zoë Kravitz, Paul Dano",
    direction: "Matt Reeves",
    synopsis:
      "In Gotham City, Batman investigates corruption while pursuing the Riddler, a serial killer.",
    genre: "Crime/Thriller",
    duration: 176,
    rating: MovieRating.DEZOITO,
    releaseDate: new Date("2025-11-14"),
    posterUrl: "https://picsum.photos/60?random=11",
    movieStatus: MovieStatus.EM_EXIBICAO,
    active: true,
  },
  {
    id: 12,
    name: "Wonka",
    originalName: "Wonka",
    casting: "Timothée Chalamet, Olivia Colman, Hugh Grant",
    direction: "Paul King",
    synopsis:
      "A whimsical prequel exploring the origins of the eccentric chocolatier Willy Wonka.",
    genre: "Fantasia/Aventura",
    duration: 115,
    rating: MovieRating.DEZ,
    releaseDate: new Date("2025-12-05"),
    posterUrl: "https://picsum.photos/60?random=12",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
  {
    id: 13,
    name: "Spider-Man: Far From Home",
    originalName: "Spider-Man: Far From Home",
    casting: "Tom Holland, Zendaya, Jake Gyllenhaal",
    direction: "Jon Watts",
    synopsis:
      "Peter Parker's European trip is interrupted by new threats that test his resolve as Spider-Man.",
    genre: "Ação/Aventura",
    duration: 129,
    rating: MovieRating.DEZ,
    releaseDate: new Date("2025-12-25"),
    posterUrl: "https://picsum.photos/60?random=13",
    movieStatus: MovieStatus.PRE_VENDA,
    active: true,
  },
];
